server:
  port: 80
spring:
  resources:
    static-locations: classpath:/resources/
security:
  social:
    filterProcessesUrl: /connet
    qq:
      app-id:
      app-secret:
      providerId:
    github:
      app-id: 2b0fe16de4597db23a12
      app-secret: 8fed4616eaf29b3252ff5d730817a390512525b3
      providerId: github