server:
  port: 80
spring:
  resources:
    static-locations: classpath:/resources/
security:
  social:
    filterProcessesUrl: /connet
    qq:
      app-id:
      app-secret:
      providerId:
    github:
      app-id: cb5001dd6b2a532a4633
      app-secret: 60ca49dc9e6993158cff497a88f52f49ed469e18
      providerId: github